//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoprite.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiURL
    {
        public int id { get; set; }
        public string baseURL { get; set; }
        public string TransactionType { get; set; }
    }
}
