//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoprite.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBatch
    {
        public int id { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string OriginalOrderXML { get; set; }
        public string Status { get; set; }
        public string Orders { get; set; }
    }
}
