//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoprite.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string OrderNumber { get; set; }
        public string OrderFile { get; set; }
        public string Vendor { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
    }
}
