//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoprite.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Enabled = 0;
            this.EnableClaims = 0;
        }
    
        public int id { get; set; }
        public string VendorName { get; set; }
        public string VendorUserName { get; set; }
        public string VendorPassWord { get; set; }
        public Nullable<int> Enabled { get; set; }
        public Nullable<int> EnableClaims { get; set; }
        public Nullable<System.DateTime> LastActionDate { get; set; }
    }
}
